/**
 * =====================================================
 * SERVICE MODEL
 * =====================================================
 * Represents a salon service (haircut, facial, etc.)
 */

const mongoose = require("mongoose");

const ServiceSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true,
      // e.g. "Haircut", "Beard Trim", "Facial"
    },
    nameHindi: {
      type: String,
      trim: true,
      // e.g. "बाल कटाई" - optional Hindi name for bilingual bots
    },
    description: {
      type: String,
      trim: true,
    },
    price: {
      type: Number,
      required: true,
      min: 0,
      // In Indian Rupees (₹)
    },
    durationMinutes: {
      type: Number,
      required: true,
      default: 30,
      // How long this service takes
    },
    emoji: {
      type: String,
      default: "✂️",
      // Used in WhatsApp messages
    },
    isActive: {
      type: Boolean,
      default: true,
      // Set to false to hide from menu without deleting
    },
    displayOrder: {
      type: Number,
      default: 0,
      // Controls order in WhatsApp menu
    },
    category: {
      type: String,
      enum: ["hair", "beard", "skin", "combo", "other"],
      default: "hair",
    },
  },
  {
    timestamps: true,
  }
);

const Service = mongoose.model("Service", ServiceSchema);

// =====================================================
// REVIEW MODEL
// =====================================================

const ReviewSchema = new mongoose.Schema(
  {
    booking: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Booking",
      required: true,
    },
    customer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Customer",
      required: true,
    },

    // --- Rating ---
    rating: {
      type: Number,
      min: 1,
      max: 5,
      required: true,
    },
    reviewText: {
      type: String,
      trim: true,
    },

    // --- AI-generated reply suggestion ---
    aiReplySuggestion: {
      type: String,
      // Generated by Claude AI - shown to salon owner
    },
    ownerReply: {
      type: String,
      // If owner chooses to reply
    },

    // Source: "whatsapp" or "manual"
    source: {
      type: String,
      default: "whatsapp",
    },
  },
  {
    timestamps: true,
  }
);

const Review = mongoose.model("Review", ReviewSchema);

module.exports = { Service, Review };
